Acme\IssueBundle\Entity\IssueLine:
    type: entity
    table: issue_line
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        quantity:
            type: decimal
            nullable: false
        issueTo:
            column: issue_to
            type: string
            nullable: false
        referenceNumber:
            column: reference_number
            type: integer
            nullable: false
    manyToOne:
        issue:
            targetEntity: Acme\IssueBundle\Entity\Issue
            nullable: false
        product:
            targetEntity: Acme\SetupBundle\Entity\Product
            nullable: false
