Acme\IssueBundle\Entity\IssueLine:
    type: entity
    table: issue_line
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        quantity:
            type: decimal
        issueTo:
            column: issue_to
            type: string
        referenceNumber:
            column: reference_number
            type: integer
    manyToOne:
        issue:
            targetEntity: Acme\IssueBundle\Entity\Issue
        product:
            targetEntity: Acme\SetupBundle\Entity\Product