Acme\IssueBundle\Entity\Issue:
    type: entity
    table: issue
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        issueDate:
            type: date
            column: issue_date
        status:
            type: boolean
            nullable: false
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    manyToOne:
        company:
            targetEntity: Acme\SetupBundle\Entity\Company
            nullable: false
        depot:
            targetEntity: Acme\SetupBundle\Entity\Depot
            nullable: false
        createdBy:
            targetEntity: Acme\UserBundle\Entity\User
            joinColumn:
                name: created_by
        updatedBy:
            targetEntity: Acme\UserBundle\Entity\User
            joinColumn:
                name: updated_by
    lifecycleCallbacks: {  }
