Acme\IssueBundle\Entity\Issue:
    type: entity
    table: issue
    repositoryClass: Acme\IssueBundle\Repository\IssueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        issueDate:
            type: date
            column: issue_date
        status:
            type: boolean
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
        finalizedAt:
            column: finalized_at
            type: datetime
            nullable: true
    manyToOne:
        fromLocation:
            targetEntity: Acme\SetupBundle\Entity\Location
            joinColumn:
                name: from_location
        company:
            targetEntity: Acme\SetupBundle\Entity\Company
        depot:
            targetEntity: Acme\SetupBundle\Entity\Depot
        createdBy:
            targetEntity: Acme\UserBundle\Entity\User
            joinColumn:
                name: created_by
        updatedBy:
            targetEntity: Acme\UserBundle\Entity\User
            nullable: true
            joinColumn:
                name: updated_by
        finalizedBy:
            targetEntity: Acme\UserBundle\Entity\User
            nullable: true
            joinColumn:
                name: finalized_by
    lifecycleCallbacks:
        prePersist: [setCreatedAt]