Acme\IssueBundle\Entity\Issue:
    type: entity
    table: issue
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        issueDate:
            type: date
            column: issue_date
        status:
            type: boolean
            nullable: false
        createdAt:
            column: created_at
            type: datetime
            nullable: false
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
        finalizeDate:
            column: finalize_date
            type: datetime
            nullable: true
    manyToOne:
        fromLocation:
            targetEntity: Acme\SetupBundle\Entity\Location
            joinColumn:
                name: from_location
        company:
            targetEntity: Acme\SetupBundle\Entity\Company
            nullable: false
        depot:
            targetEntity: Acme\SetupBundle\Entity\Depot
            nullable: false
        createdBy:
            targetEntity: Acme\UserBundle\Entity\User
            joinColumn:
                name: created_by
        updatedBy:
            targetEntity: Acme\UserBundle\Entity\User
            nullable: true
            joinColumn:
                name: updated_by
        finalizedBy:
            targetEntity: Acme\UserBundle\Entity\User
            nullable: true
            joinColumn:
                name: finalized_by
    lifecycleCallbacks:
        prePersist: [setCreatedAt]
        preUpdate: [setupdatedAt]