Acme\IssueBundle\Entity\Issue:
    type: entity
    table: issue
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        issueDate:
            type: date
            column: issue_date
        company:
            type: string
            length: 255
        depot:
            type: string
            length: 255
        status:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
