Acme\IssueBundle\Entity\IssueLine:
    type: entity
    table: issue_line
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        quantity:
            type: decimal
            scale: 4
        issueTo:
            column: issue_to
            type: string
            nullable: false
    manyToOne:
        issue:
            targetEntity: Acme\IssueBundle\Entity\Issue
            nullable: false
        product:
            targetEntity: Acme\SetupBundle\Entity\Product
            nullable: false
        referenceNumber:
            targetEntity: Acme\PurchaseBundle\Entity\PurchaseLine
            inversedBy: issueLines
            nullable: false
            joinColumn:
              name: reference_number
              referencedColumnName: id