acme_report_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeReportBundle:Default:index }

purchase_report:
    pattern: /purchase
    defaults: { _controller: AcmeReportBundle:Report:purchase }

issue_report:
    pattern: /issue
    defaults: { _controller: AcmeReportBundle:Report:issue }

print_issue_report:
    pattern: /issueprint/{from}/{to}
    defaults: { _controller: "AcmeReportBundle:Report:printIssueReport", from: "", to: ""}