acme_setup_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeSetupBundle:Default:index }

AcmeSetupBundle_depot:
    resource: "@AcmeSetupBundle/Resources/config/routing/depot.yml"
    prefix:   /depot

AcmeSetupBundle_company:
    resource: "@AcmeSetupBundle/Resources/config/routing/company.yml"
    prefix:   /company

AcmeSetupBundle_product:
   resource: "@AcmeSetupBundle/Resources/config/routing/product.yml"
   prefix:   /product

AcmeSetupBundle_supplier:
    resource: "@AcmeSetupBundle/Resources/config/routing/supplier.yml"
    prefix:   /supplier