acme_widget_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeWidgetBundle:Default:index }

AcmeWidgetBundle_lasttab:
  pattern:  /last-tab
  defaults: { _controller: AcmeWidgetBundle:LastTab:lastTab }

AcmeWidgetBundle_stateoverview:
    pattern:    /state-overview
    defaults:   { _controller:  AcmeWidgetBundle:StateOverview:stateOverview }

AcmeWidgetBundle_workprogress:
    pattern:    /work-progress
    defaults:   { _controller:  AcmeWidgetBundle:WorkProgress:workProgress }

AcmeWidgetBundle_lockscreen:
    pattern:    /lock-screen
    defaults:   { _controller:  AcmeWidgetBundle:LockScreen:lockScreen }

AcmeWidgetBundle_searchstatistics:
    resource: "@AcmeWidgetBundle/Resources/config/routing/searchstatistics.yml"
    prefix:   /search

acme_widget_available_product:
    pattern:    /available-product
    defaults:   { _controller:  AcmeWidgetBundle:AvailableProduct:availableProduct }