acme_widget_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeWidgetBundle:Default:index }

AcmeWidgetBundle_lasttab:
  pattern:  /lasttab
  defaults: { _controller: AcmeWidgetBundle:LastTab:lastTab }

AcmeWidgetBundle_stateoverview:
    pattern:    /stateoverview
    defaults:   { _controller:  AcmeWidgetBundle:StateOverview:stateOverview }

AcmeWidgetBundle_workprogress:
    pattern:    /workprogress
    defaults:   { _controller:  AcmeWidgetBundle:WorkProgress:workProgress }

AcmeWidgetBundle_topsearch:
    pattern:    /topsearch
    defaults:   { _controller:  AcmeWidgetBundle:TopSearch:topSearchList }

AcmeWidgetBundle_lockscreen:
    pattern:    /lockscreen
    defaults:   { _controller:  AcmeWidgetBundle:LockScreen:lockScreen }

AcmeWidgetBundle_searchstatistics:
    resource: "@AcmeWidgetBundle/Resources/config/routing/searchstatistics.yml"
    prefix:   /search

searchstatistics_autocomplete:
    pattern:  /autocomplete
    defaults: { _controller: AcmeWidgetBundle:SearchStatistics:autocomplete }
    requirements: { _method: get }

acme_widget_available_product:
    pattern:    /available-product
    defaults:   { _controller:  AcmeWidgetBundle:AvailableProduct:availableProduct }