acme_widget_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeWidgetBundle:Default:index }

last_purchase:
  pattern:  /last-purchase
  defaults: { _controller: AcmeWidgetBundle:LastPurchase:lastPurchase }

state_overview:
    pattern:    /state-overview
    defaults:   { _controller:  AcmeWidgetBundle:StateOverview:totalCost }

work_progress:
    pattern:    /work-progress
    defaults:   { _controller:  AcmeWidgetBundle:WorkProgress:workProgress }


