acme_widget_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeWidgetBundle:Default:index }

acme_widget_lasttab:
  pattern:  /last-tab
  defaults: { _controller: "AcmeWidgetBundle:LastTab:lastTab" }

acme_widget_state_overview:
    pattern:    /state-overview
    defaults:   { _controller:  AcmeWidgetBundle:StateOverview:stateOverview }

acme_widget_workprogress:
    pattern:    /work-progress
    defaults:   { _controller:  "AcmeWidgetBundle:WorkProgress:workProgress" }

acme_widget_workprogress_all:
    pattern:    /work-progress-all
    defaults:   { _controller:  "AcmeWidgetBundle:WorkProgress:workProgressAll" }

acme_widget_lockscreen:
    pattern:    /lock-screen
    defaults:   { _controller:  AcmeWidgetBundle:LockScreen:lockScreen }

AcmeWidgetBundle_searchstatistics:
    resource: "@AcmeWidgetBundle/Resources/config/routing/searchstatistics.yml"
    prefix:   /search

acme_widget_available_product:
    pattern:    /available-product
    defaults:   { _controller:  AcmeWidgetBundle:AvailableProduct:availableProduct }

searchstatistics_test:
    pattern:    /test
    defaults:   { _controller:  "AcmeWidgetBundle:SearchStatistics:test" }