acme_widget_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeWidgetBundle:Default:index }

AcmeWidgetBundle_lastpurchase:
  pattern:  /lastpurchase
  defaults: { _controller: AcmeWidgetBundle:LastPurchase:lastPurchase }

AcmeWidgetBundle_stateoverview:
    resource: "@AcmeWidgetBundle/Resources/config/routing/stateOverview.yml"
    prefix:   /stateoverview

AcmeWidgetBundle_workprogress:
    pattern:    /workprogress
    defaults:   { _controller:  AcmeWidgetBundle:WorkProgress:workProgress }

