acme_widget_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeWidgetBundle:Default:index }

AcmeWidgetBundle_lastpurchase:
  pattern:  /lastpurchase
  defaults: { _controller: AcmeWidgetBundle:LastPurchase:lastPurchase }

AcmeWidgetBundle_stateoverview:
    resource: "@AcmeWidgetBundle/Resources/config/routing/stateoverview.yml"
    prefix:   /stateoverview

AcmeWidgetBundle_workprogress:
    pattern:    /workprogress
    defaults:   { _controller:  AcmeWidgetBundle:WorkProgress:workProgress }

AcmeWidgetBundle_topsearch:
    pattern:    /topsearch
    defaults:   { _controller:  AcmeWidgetBundle:TopSearch:topSearchList }

AcmeWidgetBundle_lockscreen:
    pattern:    /lockscreen
    defaults:   { _controller:  AcmeWidgetBundle:LockScreen:lockScreen }

