parameters:
#    acme_widget.example.class: Acme\WidgetBundle\Example

services:
#    acme_widget.example:
#        class: %acme_widget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
