Acme\UserBundle\Entity\User:
    type:  entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        image:
            type: string
            nullable: true
    lifecycleCallbacks:
        prePersist: [ preUpload ]
        postPersist: [ upload ]