Acme\UserBundle\Entity\User:
    type:  entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        image:
            type: string
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            nullable: false
    manyToOne:
        createdBy:
            targetEntity: Acme\UserBundle\Entity\User
            joinColumn:
                name: created_by
    lifecycleCallbacks:
        prePersist: [ preUpload,setCreatedAt ]
        postPersist: [ upload ]
        postRemove: [ removeUpload ]