Acme\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass:  Acme\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        image:
            type: string
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            nullable: false
        createdBy:
            column: created_by
            type: string
            nullable: false
    manyToMany:
        groups:
            targetEntity: Acme\UserBundle\Entity\Group
            joinTable:
                name: fos_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ preUpload,setCreatedAt ]
        postPersist: [ upload ]
        postRemove: [ removeUpload ]