acme_widget:
    resource: "@AcmeWidgetBundle/Resources/config/routing.yml"
    prefix:   /widget

acme_history:
    resource: "@AcmeHistoryBundle/Resources/config/routing.yml"
    prefix:   /history

acme_report:
    resource: "@AcmeReportBundle/Resources/config/routing.yml"
    prefix:   /report

acme_issue:
    resource: "@AcmeIssueBundle/Resources/config/routing.yml"
    prefix:   /

acme_purchase:
    resource: "@AcmePurchaseBundle/Resources/config/routing.yml"
    prefix:   /

acme_setup:
    resource: "@AcmeSetupBundle/Resources/config/routing.yml"
    prefix:   /setup

acme_dash:
    resource: "@AcmeDashBundle/Resources/config/routing.yml"
    prefix:   /

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


