acme_history:
    resource: "@AcmeHistoryBundle/Resources/config/routing.yml"
    prefix:   /history

acme_report:
    resource: "@AcmeReportBundle/Resources/config/routing.yml"
    prefix:   /

acme_issue:
    resource: "@AcmeIssueBundle/Resources/config/routing.yml"
    prefix:   /

acme_purchase:
    resource: "@AcmePurchaseBundle/Resources/config/routing.yml"
    prefix:   /

acme_setup:
    resource: "@AcmeSetupBundle/Resources/config/routing.yml"
    prefix:   /setup

acme_dash:
    resource: "@AcmeDashBundle/Resources/config/routing.yml"
    prefix:   /

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

