imports:
    - { resource: "@AcmeUserBundle/Resources/config/security.yml" }

security:
    role_hierarchy:
        ROLE_USER:
        ROLE_ENTRY:       ROLE_ENTRY
        ROLE_SETUP:       ROLE_SETUP
        ROLE_ADMIN:       [ROLE_USER, ROLE_SETUP, ROLE_ENTRY]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, role: ROLE_USER }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/purchase, role: ROLE_ENTRY }
        - { path: ^/issue, role: ROLE_ENTRY }
        - { path: ^/setup, role: ROLE_SETUP }
