imports:
    - { resource: "@AcmeUserBundle/Resources/config/security.yml" }

security:
    role_hierarchy:
        ROLE_USER:
        ROLE_PURCHASE:    ROLE_PURCHASE
        ROLE_ISSUE:       ROLE_ISSUE
        ROLE_EMAIL:       ROLE_EMAIL
        ROLE_HISTORY:     ROLE_HISTORY
        ROLE_SETUP:       ROLE_SETUP
        ROLE_REPORT:      ROLE_REPORT
        ROLE_ADMIN:       [ROLE_PURCHASE, ROLE_ISSUE, ROLE_EMAIL, ROLE_HISTORY, ROLE_SETUP, ROLE_REPORT, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, role: ROLE_USER }
        - { path: ^/purchase, role: ROLE_PURCHASE }
        - { path: ^/issue, role: ROLE_ISSUE }
        - { path: ^/email, role: ROLE_EMAIL }
        - { path: ^/history, role: ROLE_HISTORY }
        - { path: ^/setup, role: ROLE_SETUP }
        - { path: ^/report, role: ROLE_REPORT }
        - { path: ^/admin, role: ROLE_ADMIN }

