user:
    pattern:  /{page}
    defaults: { _controller: "AcmeUserBundle:User:index", page: 1 }
    requirements:
            page:  \d+

user_show:
    pattern:  /{id}/show
    defaults: { _controller: "AcmeUserBundle:User:show" }

user_new:
    pattern:  /new
    defaults: { _controller: "AcmeUserBundle:User:new" }

user_create:
    pattern:  /create
    defaults: { _controller: "AcmeUserBundle:User:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AcmeUserBundle:User:edit" }

user_update:
    pattern:  /{id}/update
    defaults: { _controller: "AcmeUserBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AcmeUserBundle:User:delete" }

user_find_username:
    pattern:    /find-username/{page}
    defaults:   { _controller:  "AcmeUserBundle:User:findUsername", page:1 }
