ra_purchase_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: RaPurchaseBundle:Default:index }

AcmePurchaseBundle_purchase:
    resource: "@AcmePurchaseBundle/Resources/config/routing/purchase.yml"
    prefix:   /purchase



