Acme_purchase_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmePurchaseBundle:Default:index }

AcmePurchaseBundle_purchase:
    resource: "@AcmePurchaseBundle/Resources/config/routing/purchase.yml"
    prefix:   /purchase

AcmePurchaseBundle_purchase_line:
    resource: "@AcmePurchaseBundle/Resources/config/routing/purchaseline.yml"
    prefix:   /history/purchase-line