parameters:
#    acme_purchase.example.class: Acme\PurchaseBundle\Example

services:
    tommygnr_datatables.post:
        class: Acme\PurchaseBundle\Datatables\PurchaseDatatable
        tags:
            - { name: tommygnr.datatable.view }
