parameters:
#    acme_purchase.example.class: Acme\PurchaseBundle\Example

services:
#    acme_purchase.example:
#        class: %acme_purchase.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
