parameters:
#    ra_purchase.example.class: Ra\Bundle\PurchaseBundle\Example

services:

    sg_datatables.post:
        class: Acme\PurchaseBundle\Repository\PostDatatable
        tags:
            - { name: sg.datatable.view }