parameters:
#    ra_purchase.example.class: Ra\Bundle\PurchaseBundle\Example

services:
#    ra_purchase.example:
#        class: %ra_purchase.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
