parameters:
#    ra_purchase.example.class: Ra\Bundle\PurchaseBundle\Example

services:
    sg_datatables.client:
        class: Acme\PurchaseBundle\Repository\ClientDatatable
        tags:
            - { name: sg.datatable.view }