Acme\InvoiceBundle\Entity\Invoice:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        address:
            type: text
        invoiceDate:
            column: invoice_date
            type: date
        invoiceStatus:
            column: invoice_status
            type: boolean
        createdAt:
            column: created_at
            type: datetime
            nullable: false          
    oneToMany:
        invoiceLines:
            targetEntity: Acme\InvoiceBundle\Entity\InvoiceLine
            mappedBy: invoice
    manyToOne:
        createdBy:
            targetEntity: Acme\UserBundle\Entity\User
            joinColumn:
                name: created_by                        
    lifecycleCallbacks: {  }
        prePersist: [setCreatedAt]