Acme\InvoiceBundle\Entity\Invoice:
    type: entity
    table: invoice
    repositoryClass: Acme\InvoiceBundle\Repository\InvoiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        address:
            type: text
        invoiceDate:
            column: invoice_date
            type: date
        invoiceStatus:
            column: invoice_status
            type: string
        subTotal:
            column: sub_total
            type: decimal
            scale: 2
            nullable: false
        discount:
            column: discount
            type: decimal
            scale: 2
            nullable: true
        vat:
            column: vat
            type: decimal
            scale: 2
            nullable: true
        grandTotal:
            column: grand_total
            type: decimal
            scale: 2
        createdAt:
            column: created_at
            type: datetime
            nullable: false
    oneToMany:
        invoiceLines:
            targetEntity: Acme\InvoiceBundle\Entity\InvoiceLine
            mappedBy: invoice
    manyToOne:
        createdBy:
            targetEntity: Acme\UserBundle\Entity\User
            joinColumn:
                name: created_by
        customer:
            targetEntity: Acme\SetupBundle\Entity\Customer
            nullable: false
    lifecycleCallbacks:
        prePersist: [setCreatedAt]