location:
    path:     /
    defaults: { _controller: "AcmeSetupBundle:Location:index" }

location_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeSetupBundle:Location:show" }

location_new:
    path:     /new
    defaults: { _controller: "AcmeSetupBundle:Location:new" }

location_create:
    path:     /create
    defaults: { _controller: "AcmeSetupBundle:Location:create" }
    requirements: { _method: post }

location_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeSetupBundle:Location:edit" }

location_update:
    path:     /{id}/update
    defaults: { _controller: "AcmeSetupBundle:Location:update" }
    requirements: { _method: post|put }

location_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeSetupBundle:Location:delete" }
