acme_invoice_invoice:
    resource: "@AcmeInvoiceBundle/Resources/config/routing/invoice.yml"
    prefix:   /invoice

acme_invoice_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeInvoiceBundle:Default:index }