Acme\PurchaseBundle\Entity\Purchase:
    type: entity
    table: purchase
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        status:
            type: smallint
            nullable: false
            default: 1
        purchaseDate:
            column: purchase_date
            type: date
            nullable: false
        createdAt:
            type: datetime
            column: created_at
    oneToMany:
        lines:
            targetEntity: Acme\PurchaseBundle\Entity\PurchaseLine
            mappedBy: purchase
    manyToOne:
        company:
            targetEntity: Acme\SetupBundle\Entity\Company
            nullable: false
        depot:
            targetEntity: Acme\SetupBundle\Entity\Depot
            nullable: false
        createdBy:
            targetEntity: Acme\UserBundle\Entity\User
            joinColumn:
                name: created_by
    lifecycleCallbacks:
