Acme\PurchaseBundle\Entity\PurchaseLine:
    type: entity
    table: purchase_line
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        quantity:
            type: integer
        price:
            type: decimal
            scale: 2
        manufacturer:
            type: string
            nullable: true
    manyToOne:
        product:
            targetEntity: Acme\SetupBundle\Entity\Product
        purchase:
            targetEntity: Acme\PurchaseBundle\Entity\Purchase