Acme\PurchaseBundle\Entity\Purchase:
    type: entity
    table: purchase
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        status:
            type: smallint
            nullable: false
            default: 1
        purchaseDate:
            column: purchase_date
            type: date
            nullable: false
        createdAt:
            column: created_at
            type: datetime
            nullable: false
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
        finalizedAt:
            column: finalized_at
            type: datetime
            nullable: true
    oneToMany:
        lines:
            targetEntity: Acme\PurchaseBundle\Entity\PurchaseLine
            mappedBy: purchase
    manyToOne:
        supplier:
            targetEntity: Acme\SetupBundle\Entity\Supplier
            nullable: false
        location:
            targetEntity: Acme\SetupBundle\Entity\Location
            nullable: false
        createdBy:
            targetEntity: Acme\UserBundle\Entity\User
            joinColumn:
                name: created_by
        updatedBy:
            targetEntity: Acme\UserBundle\Entity\User
            nullable: true
            joinColumn:
                name: updated_by
        finalizedBy:
            targetEntity: Acme\UserBundle\Entity\User
            nullable: true
            joinColumn:
                name: finalized_by
    lifecycleCallbacks:
        prePersist: [setCreatedAt]
        preUpdate: [setUpdatedAt]
