Acme\PurchaseBundle\Entity\PurchaseLine:
    type: entity
    table: purchase_line
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        quantity:
            type: decimal
            scale: 2
            nullable: false
        price:
            type: decimal
            scale: 2
            nullable: false
    manyToOne:
        product:
            targetEntity: Acme\SetupBundle\Entity\Product
            nullable: false
        purchase:
            targetEntity: Acme\PurchaseBundle\Entity\Purchase
    lifecycleCallbacks:
        prePersist: [  ]

