Acme\PurchaseBundle\Entity\Purchase:
    type: entity
    table: purchase
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        purchaseDate:
            column: purchase_date
            type: datetime
    manyToOne:
        company:
            targetEntity: Acme\SetupBundle\Entity\Company
            nullable: false
        depot:
            targetEntity: Acme\SetupBundle\Entity\Depot
            nullable: false
    lifecycleCallbacks:
        prePersist: [  ]