acme_issue_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeIssueBundle:Default:index }

AcmeIssueBundle_issue:
    resource: "@AcmeIssueBundle/Resources/config/routing/issue.yml"
    prefix:   /issue

AcmeIssueBundle_issue_line:
    resource: "@AcmeIssueBundle/Resources/config/routing/issueline.yml"
    prefix:   /issue-line

