purchase:
    pattern:  /
    defaults: { _controller: "AcmePurchaseBundle:Purchase:index" }

purchase_show:
    pattern:  /{id}/show
    defaults: { _controller: "AcmePurchaseBundle:Purchase:show" }

purchase_new:
    pattern:  /new
    defaults: { _controller: "AcmePurchaseBundle:Purchase:new" }

purchase_create:
    pattern:  /create
    defaults: { _controller: "AcmePurchaseBundle:Purchase:create" }
    requirements: { _method: post }

purchase_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AcmePurchaseBundle:Purchase:edit" }

purchase_update:
    pattern:  /{id}/update
    defaults: { _controller: "AcmePurchaseBundle:Purchase:update" }
    requirements: { _method: post|put }

purchase_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AcmePurchaseBundle:Purchase:delete" }

purchase_line_delete:
    pattern: /{id}/ajax_line_delete
    defaults: { _controller: "AcmePurchaseBundle:Purchase:ajaxDeleteLine" }

purchase_finalize:
    pattern: /{id}/finalize
    defaults: { _controller: "AcmePurchaseBundle:Purchase:finalize" }

purchase_definalize:
    pattern: /{id}/definalize
    defaults: { _controller: "AcmePurchaseBundle:Purchase:deFinalize" }

supplier_total_purchase:
    pattern: /supplier-total-purchase
    defaults: { _controller: "AcmePurchaseBundle:Purchase:supplierTotalPurchase" }

purchase_supplier_detail:
    pattern:  /supplier-detail
    defaults: { _controller:  "AcmePurchaseBundle:Purchase:supplierDetail"  }

lankit:
    pattern:  /lankit
    defaults: { _controller: "AcmePurchaseBundle:Purchase:lankit" }

lankit_purchase_result:
    pattern:  /lankit-purchase-result
    defaults: { _controller: "AcmePurchaseBundle:Purchase:getLankitPurchaseResult" }

lankit_purchase_line_result:
    pattern:  /lankit-purchase-line-result
    defaults: { _controller: "AcmePurchaseBundle:Purchase:getLankitPurchaseLineResult" }