parameters:
#    acme_history.example.class: Acme\HistoryBundle\Example

services:
#    acme_history.example:
#        class: %acme_history.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
