Acme\SetupBundle\Entity\Customer:
    type: entity
    table: customer
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        address:
            type: text
        createdAt:
            column: created_at
            type: datetime
        createdBy:
            column: created_by
            type: string
            length: 255
    lifecycleCallbacks:
        prePersist: [setCreatedAt]
