Acme\SetupBundle\Entity\Customer:
    type: entity
    table: customer
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: false
        address:
            type: text
            nullable: false
        createdAt:
            column: created_at
            type: datetime
            nullable: false
        createdBy:
            column: created_by
            type: string
            length: 255
    lifecycleCallbacks:
        prePersist: [setCreatedAt]
