Acme\SetupBundle\Entity\Supplier:
    type: entity
    table: supplier
    repositoryClass: Acme\SetupBundle\Repository\SupplierRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        address:
            type: text
        createdAt:
            column: created_at
            type: datetime
            nullable: false
    manyToOne:
        createdBy:
            targetEntity: Acme\UserBundle\Entity\User
            joinColumn:
                name: created_by
    lifecycleCallbacks:
        prePersist: [setCreatedAt]
