acme_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeUserBundle:Default:index }

_acme_fos:
    resource: "@AcmeUserBundle/Resources/config/routing/fos.yml"
    prefix: /

AcmeUserBundle_user:
    resource: "@AcmeUserBundle/Resources/config/routing/user.yml"
    prefix:   /user


