acme_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeUserBundle:Default:index }

AcmeUserBundle_user:
    resource: "@AcmeUserBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

AcmeUserBundle_security:
    resource: "@AcmeUserBundle/Resources/config/routing/security.xml"

AcmeUserBundle_profile:
    resource: "@AcmeUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

acme_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

