security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        acme_userbundle:
            id: acme_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: .*
            form_login:
                provider:       acme_userbundle
                csrf_provider:  form.csrf_provider
                login_path:     acme_user_security_login
                use_forward:    false
                check_path:     acme_user_security_check
                failure_path:   null
            remember_me:
                key:      %secret%
                lifetime: 300000000
                path:     /
                domain:   ~                
            logout:       
                path:           acme_user_security_logout
                target:         /
            anonymous:          true
