services:
    acme_user.profile.form.type:
        class: %acme_user.my_profile_form_type%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: acme_user_profile }

    acme_user.user_provider.username:
        class: %acme_user.user_provider.username%
        arguments: [@fos_user.user_manager]