parameters:
    acme_user.my_twig_extension.class: Acme\UserBundle\Twig\MyTwigExtension

services:
    acme_user.my_twig_extension:
        class: %acme_user.my_twig_extension.class%
        tags:
            - { name: twig.extension }
