acme_dash_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeDashBundle:Default:index }

dashboard:
    pattern:  /dashboard
    defaults: { _controller: AcmeDashBundle:Dashboard:dashboard }

homepage:
    pattern:  /
    defaults: { _controller: AcmeDashBundle:Dashboard:index }


