services:
    request:
        class: %acme_dash.twig.request_extension%
    acme_dash.twig.request_extension:
        class: Acme\DashBundle\Twig\DashExtension
        arguments:  [@request]
        tags:
            - { name: twig.extension }

    acme_dash.salavert.twig_time_ago:
        class: %acme_dash.salavert.twig_time_ago%
        arguments: [@translator]
        tags:
        - { name: twig.extension }

    acme_dash.twig.my_extension:
        class: %acme_dash.twig.my_extension%
        tags:
            - { name: twig.extension }

    acme_dash.panch_shop.twig.extension:
        class: Acme\DashBundle\Twig\PanchShopExtension
        tags:
            - { name: twig.extension }

    acme_dash.status_extension:
        class: Acme\DashBundle\Twig\StatusExtension
        tags:
            - { name: twig.extension }